### ISSUE TITLE
[FEATURE]: Speed up parsing

### ISSUE THREAD

**Issue by MohamedAliRashad** [iamarunbrahma/vision-parse#1]
### Problem Statement

The processing of each page should happen in parallel

### Proposed Solution

Maybe use vllm

### Final Checklist

- [X] This feature would be useful to other users
- [X] I'm willing to help implement this feature

**Comment by iamarunbrahma** [comment]
Hello @MohamedAliRashad ,
Thank you for this feature request! Parallelizing page processing is definitely a valuable suggestion that could improve performance, especially for larger PDF documents.

Currently, I am processing the pages sequentially in a loop, because most of the end-users might not have high-end GPUs when they will be using local models from Ollama. 

As you have indicated willingness, would you be interested in starting with a small proof of concept? We could begin by implementing one of these approaches in a separate branch and measure the performance gains.
